#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDpJGWF4vUpSyZgsT6/uylFwecdaL4six8YOgy2PmPnJCmwwbI6jUuPy8LsWfc7paRsc976/8IxUGOxlxQ7EucMrz5NrfPhjUv6DDztEKNTFg2moSCdReNuBNqjmdSd1Z68uVmMFqSMfbLfds7c+Kib3UF/VreKDS5nKs6gjLlQhjwbWtBW8WAAX2c0kqr6UbiGhYPDF2eiGLjPa6donhYxdaFZwN0cIVMWY48WX51Ptd9qJTKvtE10ZOgkmKy3LZK56+V0IJ81UC/DWEmrS0nHU2lolY8vsYrDSftf+krpvhKbx76FulPV8ZGRyxbOaNU/OhifyjZ6WTpAOmdOyy9AgjTNvx8/UIdOQkKeaHMuxwRWT7FIECziM+TqCLChjrv+RpZvIPuLKLLoX/AS1FsZbd6zNN9sHfNTQMTRqfEjE+5OIlteK8VuMMM5t1QyZeusb8/Ouz0YDA5vMuxTUFxucwP7jm+FFcU4jZjgPsxz2WUPedqJgeUluuXmh/xpFFE= austria@austria-Lenovo-V14-ADA

# Esta parte escribe el archivo rancher.service el el siguiente path
write_files:
  - path: /etc/systemd/system/rancher.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=rancher-server como servicio
      Requires=docker.service
      After=docker.service

      [Service]
      Restart=on-failure
      RestartSec=10
      ExecStart=/usr/bin/docker run --name %p --rm --privileged -p 80:80 -p 443:443 -e CATTLE_BOOTSTRAP_PASSWORD=admin -v /opt/rancher:/var/lib/rancher rancher/rancher:stable
      ExecStop=-/usr/bin/docker stop -t 2 %p

      [Install]
      WantedBy=multi-user.target
runcmd:
  - export DEBIAN_FRONTEND=noninteractive
  - curl -sL https://releases.rancher.com/install-docker/${docker_version}.sh | sh
  - sudo usermod -aG docker ${username}
  - sudo systemctl start rancher