#cloud-config

package_upgrade: true

packages:
  - apache2

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDpJGWF4vUpSyZgsT6/uylFwecdaL4six8YOgy2PmPnJCmwwbI6jUuPy8LsWfc7paRsc976/8IxUGOxlxQ7EucMrz5NrfPhjUv6DDztEKNTFg2moSCdReNuBNqjmdSd1Z68uVmMFqSMfbLfds7c+Kib3UF/VreKDS5nKs6gjLlQhjwbWtBW8WAAX2c0kqr6UbiGhYPDF2eiGLjPa6donhYxdaFZwN0cIVMWY48WX51Ptd9qJTKvtE10ZOgkmKy3LZK56+V0IJ81UC/DWEmrS0nHU2lolY8vsYrDSftf+krpvhKbx76FulPV8ZGRyxbOaNU/OhifyjZ6WTpAOmdOyy9AgjTNvx8/UIdOQkKeaHMuxwRWT7FIECziM+TqCLChjrv+RpZvIPuLKLLoX/AS1FsZbd6zNN9sHfNTQMTRqfEjE+5OIlteK8VuMMM5t1QyZeusb8/Ouz0YDA5vMuxTUFxucwP7jm+FFcU4jZjgPsxz2WUPedqJgeUluuXmh/xpFFE= austria@austria-Lenovo-V14-ADA


write_files:
  - path: /etc/apache2/sites-available/web1.conf
    content: |
      <VirtualHost *:80>
        ServerName saez912.com
        ServerAlias www.saez912.com
        DocumentRoot /var/www/web1
      </VirtualHost>
  - path: /etc/apache2/sites-available/web2.conf
    content: |
      <VirtualHost *:80>
        ServerName vmerino.cf
        ServerAlias www.vmerino.cf
        DocumentRoot /var/www/web2
      </VirtualHost>
  

runcmd:
  - a2dissite 000-default.conf
  - a2ensite web1.conf
  - a2ensite web2.conf
  - systemctl restart apache2
  - sudo mkdir /var/www/web1
  - sudo mkdir /var/www/web2
  - sleep 60
  - git clone https://github.com/marcsaez/website.git
  - cp -r ~/website/* /var/www/web1
  - git clone https://github.com/VictorMerinoRodriguez/Landing-page.git 
  - cp -r ~/Landing-page/* /var/www/web2 
