#cloud-config

package_upgrade: true

packages:
  - apache2

write_files:
  - path: /etc/apache2/sites-available/web1.conf
    content: |
      <VirtualHost *:80>
        ServerName msaez1.cf
        ServerAlias www.msaez1.cf
        DocumentRoot /var/www/web1
      </VirtualHost>
  - path: /etc/apache2/sites-available/web2.conf
    content: |
      <VirtualHost *:80>
        ServerName vmerino.cf
        ServerAlias www.vmerino.cf
        DocumentRoot /var/www/web2
      </VirtualHost>
  

runcmd:
  - a2dissite 000-default.conf
  - a2ensite web1.conf
  - a2ensite web2.conf
  - systemctl restart apache2
  - sudo mkdir /var/www/web1
  - sudo mkdir /var/www/web2

